name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: pip install poetry

    - name: Configure Poetry Environment
      run: poetry install --no-interaction

    - name: Run tests with coverage
      continue-on-error: true
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run pytest --cov=abbsolve --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

    - name: Build package
      run: poetry build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: abbsolve-package
          path: dist/